title: Beaver Blog
url: "https://blog.beavernotes.com"

# Build settings
timezone: Europe/Rome
markdown: kramdown
include:
  - _post

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-postcss
  - jemoji

postcss:
  cache: false